# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: guide.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'guide.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bguide.proto\x12\tbeefguide\"\x9f\x01\n\nClimateDay\x12\x0b\n\x03wts\x18\x01 \x01(\x05\x12\n\n\x02yr\x18\x02 \x01(\x05\x12\x0b\n\x03\x64oy\x18\x03 \x01(\x05\x12\x0b\n\x03rad\x18\x04 \x01(\x01\x12\x0c\n\x04mint\x18\x05 \x01(\x01\x12\x0c\n\x04maxt\x18\x06 \x01(\x01\x12\x0b\n\x03vpr\x18\x07 \x01(\x01\x12\x0c\n\x04wind\x18\x08 \x01(\x01\x12\x0c\n\x04rain\x18\t \x01(\x01\x12\x0b\n\x03\x61ha\x18\n \x01(\x01\x12\x0c\n\x04okta\x18\x0b \x01(\x01\"g\n\x0cGuideRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x13\n\x0bscenario_id\x18\x02 \x01(\x05\x12.\n\x0f\x63limate_history\x18\x03 \x03(\x0b\x32\x15.beefguide.ClimateDay\"*\n\nTargetBand\x12\r\n\x05lower\x18\x01 \x01(\x01\x12\r\n\x05upper\x18\x02 \x01(\x01\"\x84\x01\n\x0e\x45xpectedEffect\x12\x1d\n\x15\x62\x65\x65\x66_gain_kg_next_24h\x18\x01 \x01(\x01\x12\"\n\x1a\x66\x65\x65\x64_intake_kg_dm_next_24h\x18\x02 \x01(\x01\x12/\n\'feed_efficiency_change_g_beef_per_kg_dm\x18\x03 \x01(\x01\"\x84\x03\n\rGuideResponse\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x13\n\x0bscenario_id\x18\x02 \x01(\x05\x12\x30\n\x11\x61ir_temperature_c\x18\x03 \x01(\x0b\x32\x15.beefguide.TargetBand\x12\x34\n\x15relative_humidity_pct\x18\x04 \x01(\x0b\x32\x15.beefguide.TargetBand\x12/\n\x10\x61ir_velocity_mps\x18\x05 \x01(\x0b\x32\x15.beefguide.TargetBand\x12\x10\n\x08priority\x18\x06 \x01(\t\x12\x32\n\x0f\x65xpected_effect\x18\x07 \x01(\x0b\x32\x19.beefguide.ExpectedEffect\x12 \n\x18\x64ominant_limiting_factor\x18\x08 \x01(\t\x12\x12\n\nrisk_level\x18\t \x01(\t\x12\x16\n\x0e\x65\x63onomic_score\x18\n \x01(\x01\x12\x0e\n\x06\x65ngine\x18\x0b \x01(\t\x12\r\n\x05notes\x18\x0c \x01(\t2V\n\x10\x42\x65\x65\x66GuideService\x12\x42\n\rGetDailyGuide\x12\x17.beefguide.GuideRequest\x1a\x18.beefguide.GuideResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'guide_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CLIMATEDAY']._serialized_start=27
  _globals['_CLIMATEDAY']._serialized_end=186
  _globals['_GUIDEREQUEST']._serialized_start=188
  _globals['_GUIDEREQUEST']._serialized_end=291
  _globals['_TARGETBAND']._serialized_start=293
  _globals['_TARGETBAND']._serialized_end=335
  _globals['_EXPECTEDEFFECT']._serialized_start=338
  _globals['_EXPECTEDEFFECT']._serialized_end=470
  _globals['_GUIDERESPONSE']._serialized_start=473
  _globals['_GUIDERESPONSE']._serialized_end=861
  _globals['_BEEFGUIDESERVICE']._serialized_start=863
  _globals['_BEEFGUIDESERVICE']._serialized_end=949
# @@protoc_insertion_point(module_scope)
